# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m-FeV18q0Pn0TwPtO8X9gOF7HhgzPSlK
"""

import os

# Load your API keys from env vars or here directly (not recommended for prod)
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")